Sprint 5/step 1
MilaSergeeva/react-burger pull request #5
Opened 2022-12-14 02:38 UTC by MilaSergeeva

2022-12-14 04:08 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь в приложении есть лента заказа;
- Используются веб-сокеты;

### **Но есть замечания, которые нужно исправить:**

- при открытии модального окна в Истории заказов, каждый рах создаётся новое сокет-соединение, соединение должно открываться только 1 раз, когда вы переходите на страницу `История заказов`.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-14 04:08 UTC, ArslanMustafin commented on src/components/Order/Order.tsx
> +  console.log(order, orders, wsConnected);
**Надо исправить:**

в приложении не должно быть логов или дебаггеров.

2022-12-14 04:08 UTC, ArslanMustafin commented on src/services/middleware/webSocketMiddleware.ts
> +  }
**Можно лучше:**

Можно сразу написать: 

```js
const auth = localStorage.getItem("refreshToken") !== null
```

2022-12-14 04:08 UTC, ArslanMustafin commented on src/services/reducers/ws.ts
> +        error: undefined,
**Можно лучше:** 

здесь и далее.

Тут лучше либо не передавать вообще error, либо передавать `null`.

2022-12-14 04:08 UTC, ArslanMustafin commented on src/components/OrdersCardList/OrdersCardList.tsx
> +  }, [dispatch]);
**Можно лучше:**

тут лучше создать отдельную страницу, а не завязывать функционал сокета на компоненте, тем более он используется на других страницах.

2022-12-14 04:08 UTC, ArslanDev666 commented on src/services/middleware/webSocketMiddleware.ts
> +        dispatch({ type: WS_CONNECTION_CLOSED, payload: event });
**Можно лучше:**

Здесь и далее. socketAuth.

если оставить этот экшен, то у вас будет он срабатывать 2 раза. 
Сначало сработает в `useEffect` на странице, которую вы закрыли, а потом тут. И получается некое дублирование) это не критично, так что по желанию можно убрать. 

Или как вариант, добавить ещё экшен, чтобы точно знать что сокет закрылся.

2022-12-14 04:08 UTC, ArslanDev666 commented on src/services/middleware/webSocketMiddleware.ts
> +      socket = new WebSocket(`${WS_URL_ALL}`);
**Можно лучше:**

url для сокета лучше передавать через payload, а также можно попробовать сделать 1 сокет, вместо 2.

2022-12-14 11:02 UTC, MilaSergeeva commented on src/services/reducers/ws.ts
> +        error: undefined,
done

2022-12-14 11:02 UTC, MilaSergeeva commented on src/services/middleware/webSocketMiddleware.ts
> +  }
done

2022-12-14 11:04 UTC, MilaSergeeva commented on src/components/OrdersCardList/OrdersCardList.tsx
> +  }, [dispatch]);
Извините, не поняла что имеется ввиду

2022-12-15 07:43 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Замечания с прошлого ревью были исправлены;

### **Но появилось новое замечание, которое нужно исправить:**

- У вас не загружается заказ, если открыть url `/feed/:id` или `profile/orders/:id` в новой вкладке, то будет бесконечная загрузка. Как я и раньше говорил, попробуйте просто создать для них отдельную страницу и там реализовать логику с сокетами.

например:

```js
// App.tsx
<ProtectedRoute onlyForAuth={true} path='/profile/orders/:id' exact={true}>
	<OrderPage />
</ProtectedRoute>;
// OrderPage.tsx
const OrderPage = () => {
	// подключение сокетов
	return (
		<Modal isOpened={true} onClose={handleModalClose} header={''}>
			<Order />
		</Modal>
	);
};
```

2022-12-15 07:45 UTC, ArslanDev666 commented on src/components/OrdersCardList/OrdersCardList.tsx
> +  }, [dispatch]);
Попробовал объяснить в общем комментарии.

2022-12-16 10:07 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания с прошлого ревью были исправлены.

2022-12-19 19:17 UTC, merged